"""Write all registered tables to outputs/stats_results.xlsx (Arial, one sheet per table)."""
import numpy as np
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from .utils import DIAG, LINEARITY, OUT_DIR, TABLE_NOTES, TABLES, add_table

F = "Arial"


def write():
    add_table("model_diagnostics", pd.DataFrame(DIAG),
              "Every fitted model: N, events, df, events per variable (EPV), convergence, max VIF, sparse cells.")
    add_table("linearity_checks", pd.DataFrame(LINEARITY),
              "Restricted cubic spline (4 knots) test of non-linearity for each continuous term (robust Wald test).")
    wb = Workbook()
    ws0 = wb.active
    ws0.title = "README"
    ws0["A1"] = "Uterine pathology & stroke — statistical results"
    ws0["A1"].font = Font(name=F, bold=True, size=12)
    ws0["A2"] = ("Generated by analysis/run_all.py. No MRN/DOB in any sheet. OR (95% CI) columns are text; "
                 "numeric OR / CI low / CI high / p columns are provided alongside.")
    ws0["A2"].font = Font(name=F, size=10)
    ws0.append([])
    ws0.append(["Sheet", "Contents"])
    for c in ws0[4]:
        c.font = Font(name=F, bold=True, color="FFFFFF")
        c.fill = PatternFill("solid", fgColor="2A78D6")
    for name in TABLES:
        ws0.append([name, TABLE_NOTES.get(name, "")])
    for row in ws0.iter_rows(min_row=5):
        for c in row:
            c.font = Font(name=F, size=10)
    ws0.column_dimensions["A"].width = 30
    ws0.column_dimensions["B"].width = 120

    thin = Side(style="thin", color="D9D8D4")
    for name, df in TABLES.items():
        ws = wb.create_sheet(name)
        ws["A1"] = name
        ws["A1"].font = Font(name=F, bold=True, size=11)
        ws["A2"] = TABLE_NOTES.get(name, "")
        ws["A2"].font = Font(name=F, italic=True, size=9, color="52514E")
        hdr_row = 4
        df = df.copy()
        for j, col in enumerate(df.columns, start=1):
            c = ws.cell(row=hdr_row, column=j, value=str(col))
            c.font = Font(name=F, bold=True, color="FFFFFF", size=10)
            c.fill = PatternFill("solid", fgColor="2A78D6")
            c.alignment = Alignment(wrap_text=True, vertical="center")
        for i, rec in enumerate(df.itertuples(index=False), start=hdr_row + 1):
            for j, v in enumerate(rec, start=1):
                if isinstance(v, (float, np.floating)):
                    v = None if np.isnan(v) else round(float(v), 6)
                elif isinstance(v, (np.integer,)):
                    v = int(v)
                elif isinstance(v, (list, dict, tuple)):
                    v = str(v)
                c = ws.cell(row=i, column=j, value=v)
                c.font = Font(name=F, size=10)
                c.border = Border(bottom=thin)
        for j, col in enumerate(df.columns, start=1):
            vals = [len(str(col))] + [len(str(x)) for x in df.iloc[:, j - 1].head(200).tolist()]
            ws.column_dimensions[get_column_letter(j)].width = min(max(10, max(vals) + 2), 60)
        ws.freeze_panes = ws.cell(row=hdr_row + 1, column=1)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / "stats_results.xlsx"
    wb.save(path)
    return path
